### ISSUE TITLE
Add method to enable/disable half stars

### ISSUE THREAD

**Issue by odil-io** [kevinruscoe/acf-star-rating-field#17]
An option within ACF to either enable or disable half stars.
In my case I didn't need to use half stars so i just deleted a few lines from `input.js`.

Posted for future reference.

**Comment by kevdotbadger** [comment]
PR's welcome!

**Comment by odil-io** [comment]
I'll write something this week!

**Comment by kevdotbadger** [comment]
FYI, this is baked in now.
