### ISSUE TITLE
Compatible with WP All Import

### ISSUE THREAD

**Issue by dhunink** [kevinruscoe/acf-star-rating-field#23]
Hi!

WP All Import did not supported the Star Rating field...untill now.
I've been in touch with their developers and they have just released an update including support for this field type. Possibly worth mentioning in the Docs?

**Comment by kevdotbadger** [comment]
Hello @dhunink that's for letting me know. If you fancy writing a simple PR to add to the readme, feel free!

**Comment by youngfreshnew** [comment]
Is this compatible with WP All Export? I just did a test and I don't get the value. I get the full HTML code. Is there a way to get the value?
