### ISSUE TITLE
Compatible with Brizy

### ISSUE THREAD

**Issue by waldo-dueck** [kevinruscoe/acf-star-rating-field#25]
Hi,
you’ve build an excellent star-rating plugin for acf.
On my Website I work with Brizy.
So far I didn’t find a way how your plugin is compatible with Brizy.

Du you know a way that your plugin works with Brizy?

**Comment by kevinruscoe** [comment]
Hello, I'm not familiar with Brizy, but I've used all the tools ACF gave me, so if it doesn't work there's a chance it's a ACF problem.
