### ISSUE TITLE
Making rating required?

### ISSUE THREAD

**Issue by dperis** [kevinruscoe/acf-star-rating-field#27]
Hello.  Is it possible to make the rating required and display an error if a rating is not selected?  It is currently set as required in the ACF admin, but that does not seem to be working.

**Comment by bluantinoo** [comment]
Same issue here. Default Input value is zero, so it is actually always valid.

**Comment by bluantinoo** [comment]
@dperis if you still need the field to be actually required when I pushed a commit to achieve that: https://github.com/kevinruscoe/acf-star-rating-field/pull/29/commits/4cfead23c99956d289f9ec8ce264f507ae9943d2

**Comment by kevinruscoe** [comment]
Pulled, thank @bluantinoo
