### ISSUE TITLE
Star outline icon is not working

### ISSUE THREAD

**Issue by pruthvi145** [kevinruscoe/acf-star-rating-field#28]
Hey, since Font Awesome 5 is not supporting `fa fa-star-o` class for star outline icon and your plugin is importing FA5 dynamically from CDN, any solution?

Thank You :-)

**Comment by kevinruscoe** [comment]
Hello, this was written when FA5 wasn't around. I've pushed an update which allows you to upgrade to FA5, please check out the wiki (https://github.com/kevinruscoe/acf-star-rating-field/wiki/Cheat-Guide)
