### ISSUE TITLE
Please consider loading inline svg instead of fa icons in wp admin

### ISSUE THREAD

**Issue by wpsumo** [kevinruscoe/acf-star-rating-field#31]
@kevinruscoe  Please consider loading inline svg instead of fa icons in wp admin. I do not use fontawesome for this frontend or at all. So I prefer to not load it in wp admin either. Could we disable it somehow?

**Comment by kevinruscoe** [comment]
Hello, I've pushed an update which allows this. Please check out the wiki (https://github.com/kevinruscoe/acf-star-rating-field/wiki/Cheat-Guide)

**Comment by wpsumo** [comment]
@kevinruscoe Great and fast response thanks! Works great thanks!
