### ISSUE TITLE
Is this also for frontend user rating?

### ISSUE THREAD

**Issue by Borkent** [kevinruscoe/acf-star-rating-field#33]
Hi!

Question:
I installed this plugin and got it to show in the backend of my custom post type.
How would I get the rating to show on my single template so users can rate the article?

Or is this not built for frontend use?

Question 2: How would I get a top 5 article list based on rating?

Regards,
Thomas

**Comment by kevinruscoe** [comment]
TBH I haven't used this on the front-end, but it was built using the official ACF skeleton-app, so the front-end form stuff should work. 

I suggest having a read through https://www.advancedcustomfields.com/resources/create-a-front-end-form/. As for querying WP for things based on the field value, have a look at https://www.advancedcustomfields.com/resources/query-posts-custom-fields/
